### ISSUE TITLE
Camera position shifting

### ISSUE THREAD

**Issue by aliekiddo** [xcreatelabs/playir#61] opened 2014-08-08 20:18 UTC
When dragging the menu or swiping in-game (Race Invaders) the camera shifts causing the UI to move out of position
mostly when making big movements or near the edge of the screen
HTC One S - Android ICS
![2014-08-08 21 01 49](https://cloud.githubusercontent.com/assets/7974754/3862205/b116e0ce-1f38-11e4-87b4-142ac8fdc0a3.png)

**Comment by ashcairo** [comment] 2014-08-08 20:25
Duplicate of #14 
If you manage to find concrete repo steps, please add it there.

**Closed as completed** 2014-08-08 20:25 UTC
Labels: bug, duplicate
