### ISSUE TITLE
UI Dragged out of place

### ISSUE THREAD

**Issue by drdavient** [xcreatelabs/playir#14] opened 2013-08-17 13:19 UTC
In WOF, possibly also in other games. Sometimes when you accidentally drag on the user interface rather than tap, the ui gets rotated in 3D. It fixes itself shortly after.
Noticed in Character selection and in fight.

**Comment by ashcairo** [comment] 2013-08-17 16:47
@drdavient Is there a specific dragging action you need to do to reproduce this issue?
A video would be useful

**Comment by ashcairo** [comment] 2013-12-17 04:12
Unable to reproduce.

**Comment by drdavient** [comment] 2013-12-23 16:52
This is still occurring from time to time. I saw it on both desktops and
devices on Thursday. However, like you I am unable to reliably reproduce
this issue.

Dave Cooper
¿â°Ø´óÎÀ

http://www.kickstarter.com/projects/920406198/playir-drag-and-drop-3d-multiplayer-game-designer
Making multiplayer game design, and development easy!

Please support us on
indiegogohttp://www.indiegogo.com/projects/playir-open-source-games-real-time-design-tools

http://www.indiegogo.com/projects/playir-open-source-games-real-time-design-tools

China +86 186 1176 4913
UK     +44  77  6156 4320
dave.e.cooper@gmail.com
http://drdavient.com
http://redpirates.org

**Comment by ashcairo** [comment] 2013-12-23 17:04
Ok, I'll keep it open in case we find a repro.

**Comment by aliekiddo** [comment] 2014-08-08 20:37
I can reliably get this to occur when dragging from the extreme right, at the end of the menu, it doesn't happen on the left side, the UI always shifts position in the same way
![2014-08-08 21 32 33](https://cloud.githubusercontent.com/assets/7974754/3862426/aacc6542-1f3b-11e4-9da3-38e8d63aa476.png)

**Comment by ashcairo** [comment] 2014-08-08 20:40
Video please

**Comment by aliekiddo** [comment] 2014-08-08 21:12
http://youtu.be/tJTPITRrIrE

**Comment by ashcairo** [comment] 2014-10-22 03:28
@foyzul-playir has this ever happened to you on iOS?

**Comment by aliekiddo** [comment] 2014-10-22 19:02
@ashcairo @foyzul-playir
I can't reproduce it on ipdad or my macbook (I can't remember if it happened on PC before)
I can't get it to reproduce on android atm

**Comment by foyzul-playir** [comment] 2014-10-22 21:38
Do you know exactly how it happens? Also which UI is it; the main editor screen with the play-field, where you drag and drop stuff?

---

**Comment by ashcairo** [comment] 2014-10-23 00:34
@foyzul-playir see http://youtu.be/tJTPITRrIrE

**Comment by ashcairo** [comment] 2014-10-23 00:36
@aliekiddo let me know if you manage to reproduce this, I still can't reproduce this on my HTC One.

**Comment by aliekiddo** [comment] 2014-10-23 15:36
Turns out I can reproduce it after looking at the vid again, by dragging diagonally inwards from the bottom right screen corner.

If it helps, sometimes everything moves together
sometimes the game text UI stays in place
and sometimes just the text UI moves

This is on my HTC One S

![2014-10-23 16 18 08](https://cloud.githubusercontent.com/assets/7974754/4755880/1a0d2338-5ac9-11e4-9678-4f80d5166dd9.png)
![2014-10-23 16 19 30](https://cloud.githubusercontent.com/assets/7974754/4755883/1c123eca-5ac9-11e4-8336-c90a6677c6eb.png)
![2014-10-23 16 19 41](https://cloud.githubusercontent.com/assets/7974754/4755886/1e4f78d8-5ac9-11e4-9b3e-e30cf170e146.png)

**Comment by foyzul-playir** [comment] 2014-10-24 18:42
I couldn't reproduce this on the iPhone, unless you've just fixed it recently 

---

**Comment by ashcairo** [comment] 2014-11-21 04:14
WOOHOO! I FINALLY MANAGED TO REPRODUCE THIS!!
(On a Samsung device). Fix coming soon.

**Comment by ashcairo** [comment] 2014-11-21 05:46
Bug in underlying Maths library of some variations of Android. Now fixed.

**Closed as completed** 2014-11-21 05:46 UTC
Labels: bug, fixed
